---
name: Auto Semver
on:
  pull_request_target:
    types: closed
    branches:
      - main
jobs:
  update:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Auto Semver
        uses: discoverygarden/auto-semver@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
